FROM centos:7.9.2009
RUN yum install -y httpd \
zip \
unzip
ADD https://www.free-css.com/assets/files/free-css-templates/download/page279/wedding-planner.zip/var/www/html/=
WORKDIR /var/www/html
RUN unzip wedding-planner.zip
RUN cp -rvf free-wedding-website-template/* .
RUN rm -rf free-wedding-website-template wedding-planner.zip
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80